<a href="https://colab.research.google.com/github/guslimaa777/45419370/blob/main/aula3_machine_learning_industria_aluno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 3 — Preparação final da base para modelagem

## Contexto
Nesta aula, continuaremos o projeto de **Machine Learning Aplicada à Indústria**, utilizando a base de dados de uma planta química com foco no monitoramento do **status da instrumentação** de um sistema de controle de vazão de produtos químicos.

## Foco da aula
- normalização e padronização
- codificação de variáveis categóricas
- preparação final da base para modelagem

## Resultado esperado
Ao final da aula, a turma deverá gerar uma base pronta para modelagem, com variáveis numéricas escaladas, variáveis categóricas codificadas e separação entre atributos preditores e variável-alvo.

## Orientações ao aluno
Complete as células indicadas com base na demonstração guiada do professor.  
Registre observações técnicas sempre que solicitado.

In [47]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

pd.set_option('display.max_columns', None)

## 1. Carregamento da base

Tente carregar primeiro a base tratada da aula anterior.  
Se necessário, utilize a base bruta para fins de prática.

In [48]:
# Complete o nome do arquivo tratado, se necessário

arquivo_tratado = 'dados_aula1_machine_learning_industria_tratado.csv'
arquivo_bruto = 'dados_aula1_machine_learning_industria.csv'

try:
    df = pd.read_csv(arquivo_tratado)
    print(f'Base carregada: {arquivo_tratado}')
except:
    df = pd.read_csv(arquivo_bruto)
    print('Base bruta carregada para fins didáticos.')

df.head()

Base bruta carregada para fins didáticos.

,timestamp,lote_producao,operador,modo_controle,status_valvula,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3,status_instrumentacao
0,2026-01-10 08:00:00,Lote_A,op_b,automatico,normal,121.44,128.08,3.518,95.00,56.97,2.960,220.8,7.09,1.069,estavel
1,2026-01-10 09:00:00,Lote_D,op_c,cascata,normal,126.17,119.32,4.616,43.34,63.26,2.532,402.1,6.99,1.053,inspecao
2,2026-01-10 10:00:00,Lote_B,op_d,manual,intermitente,128.54,129.11,4.118,40.67,63.14,2.182,284.1,6.72,1.021,inspecao
3,2026-01-10 11:00:00,Lote_C,op_a,automatico,intermitente,106.50,102.68,3.547,43.94,64.75,2.772,486.3,6.67,1.093,inspecao
4,2026-01-10 12:00:00,Lote_C,op_a,automatico,normal,101.59,NaN,4.085,102.00,83.82,3.173,283.3,6.66,1.004,estavel

## 2. Inspeção inicial da base

Preencha os comandos para visualizar:
- dimensão da base;
- tipos de dados;
- nomes das colunas.

In [49]:


# Exiba a dimensão da base
print('Dimensão da base:', df.shape)

# Exiba os tipos de dados
display(df.dtypes)

# Exiba os nomes das colunas
display(pd.DataFrame({'coluna': df.columns}))

Dimensão da base: (188, 15)

timestamp                   object
lote_producao               object
operador                    object
modo_controle               object
status_valvula              object
setpoint_vazao_l_min       float64
vazao_medida_l_min         float64
pressao_linha_bar          float64
temperatura_processo_c     float64
abertura_valvula_pct       float64
vibracao_bomba_mm_s        float64
tempo_resposta_ms          float64
ph_produto                 float64
densidade_produto_g_cm3    float64
status_instrumentacao       object
dtype: object

                     coluna
0                 timestamp
1             lote_producao
2                  operador
3             modo_controle
4            status_valvula
5      setpoint_vazao_l_min
6        vazao_medida_l_min
7         pressao_linha_bar
8    temperatura_processo_c
9      abertura_valvula_pct
10      vibracao_bomba_mm_s
11        tempo_resposta_ms
12               ph_produto
13  densidade_produto_g_cm3
14    status_instrumentacao

## 3. Identificação de colunas numéricas e categóricas

In [50]:

colunas_numericas = df.select_dtypes(include=['number']).columns.tolist()
colunas_categoricas = df.select_dtypes(include=['object', 'category']).columns.tolist()

print('Colunas numéricas:', colunas_numericas)
print('\nColunas categóricas:', colunas_categoricas)

Colunas numéricas: ['setpoint_vazao_l_min', 'vazao_medida_l_min', 'pressao_linha_bar', 'temperatura_processo_c', 'abertura_valvula_pct', 'vibracao_bomba_mm_s', 'tempo_resposta_ms', 'ph_produto', 'densidade_produto_g_cm3']

Colunas categóricas: ['timestamp', 'lote_producao', 'operador', 'modo_controle', 'status_valvula', 'status_instrumentacao']

**Registro do aluno:**  
Quais colunas parecem mais importantes para o problema industrial?  
- Resposta:

## 4. Separação da variável-alvo

Utilize como variável-alvo a coluna `status_instrumentacao`.

In [51]:

alvo = 'status_instrumentacao'

X = df.drop(columns=[alvo]).copy()
y = df[alvo].copy()

print('Dimensão de X:', X.shape)
print('Dimensão de y:', y.shape)

display(
    y.value_counts(dropna=False)
     .rename_axis('classe')
     .reset_index(name='quantidade')
)

Dimensão de X: (188, 14)
Dimensão de y: (188,)

     classe  quantidade
0  inspecao         118
1   estavel          70

## 5. Separação entre dados numéricos e categóricos

In [53]:
X_numerico = X.select_dtypes(include=['int64', 'float64']).copy()
X_categorico = X.select_dtypes(include=["object", "category"]).copy()

print('dimensao de x_numerico:', X_numerico.shape)
print('dimensao de x_categorico:', X_numerico.shape)

display(X_categorico.head())
display(X_categorico.head())

dimensao de x_numerico: (188, 9)
dimensao de x_categorico: (188, 9)

             timestamp lote_producao operador modo_controle status_valvula
0  2026-01-10 08:00:00        Lote_A     op_b    automatico         normal
1  2026-01-10 09:00:00        Lote_D     op_c       cascata         normal
2  2026-01-10 10:00:00        Lote_B     op_d        manual   intermitente
3  2026-01-10 11:00:00        Lote_C     op_a    automatico   intermitente
4  2026-01-10 12:00:00        Lote_C     op_a    automatico         normal

             timestamp lote_producao operador modo_controle status_valvula
0  2026-01-10 08:00:00        Lote_A     op_b    automatico         normal
1  2026-01-10 09:00:00        Lote_D     op_c       cascata         normal
2  2026-01-10 10:00:00        Lote_B     op_d        manual   intermitente
3  2026-01-10 11:00:00        Lote_C     op_a    automatico   intermitente
4  2026-01-10 12:00:00        Lote_C     op_a    automatico         normal

## 6. Normalização

Complete o código para aplicar `MinMaxScaler` nas variáveis numéricas.

In [54]:
scaler_minmax = MinMaxScaler()

X_normalizado_array = scaler_minmax.fit_transform(X_numerico)

X_normalizado = pd.DataFrame(
    X_normalizado_array,
    columns=X_numerico.columns,
    index=X_numerico.index
)

X_normalizado.head()

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3
0,0.466897,0.539943,0.095683,0.821280,0.479390,0.295387,0.066209,0.690789,0.648649
1,0.537907,0.414979,0.244282,0.205767,0.556786,0.246270,0.198555,0.625000,0.562162
2,0.573487,0.554636,0.176885,0.173954,0.555309,0.206105,0.112417,0.447368,0.389189
3,0.242606,0.177603,0.099608,0.212916,0.575120,0.273812,0.260019,0.414474,0.778378
4,0.168894,NaN,0.172418,0.904682,0.809770,0.319830,0.111833,0.407895,0.297297

## 7. Comparação antes e depois da normalização

In [55]:
comparacao_normalizacao = pd.DataFrame({
    'valor_original_min': [X_numerico['setpoint_vazao_l_min'].min()],
    'valor_original_max': [X_numerico['setpoint_vazao_l_min'].max()],
    'valor_normalizado_min': [X_normalizado['setpoint_vazao_l_min'].min()],
    'valor_normalizado_max': [X_normalizado['setpoint_vazao_l_min'].max()]
})

display(comparacao_normalizacao)

,valor_original_min,valor_original_max,valor_normalizado_min,valor_normalizado_max
0,90.34,156.95,0.0,1.0

**Registro do aluno:**  
O que mudou nos dados após a normalização?  
- Resposta:

## 8. Padronização

Agora aplique `StandardScaler` às variáveis numéricas.

In [56]:

scaler_standard = StandardScaler()

X_padronizado_array = scaler_standard.fit_transform(X_numerico)

X_padronizado = pd.DataFrame(
    X_padronizado_array,
    columns=X_numerico.columns,
    index=X_numerico.index
)

X_padronizado.head()

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3
0,0.196487,0.617912,-0.520001,5.454692,-0.091729,0.652787,-0.904175,0.909975,0.931345
1,0.586374,-0.018284,0.787201,-0.056996,0.293278,0.205000,0.503087,0.588996,0.412936
2,0.781729,0.692716,0.194317,-0.341863,0.285932,-0.161181,-0.412837,-0.277647,-0.623884
3,-1.034995,-1.226766,-0.485475,0.007019,0.384480,0.456095,1.156653,-0.438136,1.708960
4,-1.439720,NaN,0.155030,6.201533,1.551742,0.875634,-0.419046,-0.470234,-1.174695

## 9. Comparação antes e depois da padronização

In [57]:

comparacao_padronizacao = pd.DataFrame({
    'media_original': X_numerico.mean(),
    'desvio_original': X_numerico.std(),
    'media_padronizada': X_padronizado.mean(),
    'desvio_padronizado': X_padronizado.std()
})

display(comparacao_padronizacao.round(4))

,media_original,desvio_original,media_padronizada,desvio_padronizado
setpoint_vazao_l_min,119.0563,12.1641,-0.0,1.0027
vazao_medida_l_min,119.5718,13.8086,0.0,1.0029
pressao_linha_bar,3.9548,0.8423,-0.0,1.0028
temperatura_processo_c,43.8742,9.3992,-0.0,1.0028
abertura_valvula_pct,58.4686,16.3810,-0.0,1.0027
vibracao_bomba_mm_s,2.3361,0.9584,0.0,1.0027
tempo_resposta_ms,337.2864,129.1972,-0.0,1.0028
ph_produto,6.8065,0.3124,-0.0,1.0028
densidade_produto_g_cm3,1.0403,0.0309,0.0,1.0027

**Registro do aluno:**  
Quando a padronização pode ser mais útil que a normalização?  
- Resposta:

## 10. Codificação de variáveis categóricas

Utilize `pd.get_dummies()` para transformar as variáveis categóricas em colunas numéricas.

In [58]:
X_categorico_codificado = pd.get_dummies(X_categorico, drop_first=False)

print('Dimensão da base categórica codificada:', X_categorico_codificado.shape)
X_categorico_codificado.head()

Dimensão da base categórica codificada: (188, 194)

,timestamp_2026-01-10 08:00:00,timestamp_2026-01-10 09:00:00,timestamp_2026-01-10 10:00:00,timestamp_2026-01-10 11:00:00,timestamp_2026-01-10 12:00:00,timestamp_2026-01-10 13:00:00,timestamp_2026-01-10 14:00:00,timestamp_2026-01-10 15:00:00,timestamp_2026-01-10 16:00:00,timestamp_2026-01-10 17:00:00,timestamp_2026-01-10 18:00:00,timestamp_2026-01-10 19:00:00,timestamp_2026-01-10 20:00:00,timestamp_2026-01-10 21:00:00,timestamp_2026-01-10 22:00:00,timestamp_2026-01-10 23:00:00,timestamp_2026-01-11 00:00:00,timestamp_2026-01-11 01:00:00,timestamp_2026-01-11 02:00:00,timestamp_2026-01-11 03:00:00,timestamp_2026-01-11 04:00:00,timestamp_2026-01-11 05:00:00,timestamp_2026-01-11 06:00:00,timestamp_2026-01-11 07:00:00,timestamp_2026-01-11 08:00:00,timestamp_2026-01-11 09:00:00,timestamp_2026-01-11 10:00:00,timestamp_2026-01-11 11:00:00,timestamp_2026-01-11 12:00:00,timestamp_2026-01-11 13:00:00,timestamp_2026-01-11 14:00:00,timestamp_2026-01-11 15:00:00,timestamp_2026-01-11 16:00:00,timestamp_2026-01-11 17:00:00,timestamp_2026-01-11 18:00:00,timestamp_2026-01-11 19:00:00,timestamp_2026-01-11 20:00:00,timestamp_2026-01-11 21:00:00,timestamp_2026-01-11 22:00:00,timestamp_2026-01-11 23:00:00,timestamp_2026-01-12 00:00:00,timestamp_2026-01-12 01:00:00,timestamp_2026-01-12 02:00:00,timestamp_2026-01-12 03:00:00,timestamp_2026-01-12 04:00:00,timestamp_2026-01-12 05:00:00,timestamp_2026-01-12 06:00:00,timestamp_2026-01-12 07:00:00,timestamp_2026-01-12 08:00:00,timestamp_2026-01-12 09:00:00,timestamp_2026-01-12 10:00:00,timestamp_2026-01-12 11:00:00,timestamp_2026-01-12 12:00:00,timestamp_2026-01-12 13:00:00,timestamp_2026-01-12 14:00:00,timestamp_2026-01-12 15:00:00,timestamp_2026-01-12 16:00:00,timestamp_2026-01-12 17:00:00,timestamp_2026-01-12 18:00:00,timestamp_2026-01-12 19:00:00,timestamp_2026-01-12 20:00:00,timestamp_2026-01-12 21:00:00,timestamp_2026-01-12 22:00:00,timestamp_2026-01-12 23:00:00,timestamp_2026-01-13 00:00:00,timestamp_2026-01-13 01:00:00,timestamp_2026-01-13 02:00:00,timestamp_2026-01-13 03:00:00,timestamp_2026-01-13 04:00:00,timestamp_2026-01-13 05:00:00,timestamp_2026-01-13 06:00:00,timestamp_2026-01-13 07:00:00,timestamp_2026-01-13 08:00:00,timestamp_2026-01-13 09:00:00,timestamp_2026-01-13 10:00:00,timestamp_2026-01-13 11:00:00,timestamp_2026-01-13 12:00:00,timestamp_2026-01-13 13:00:00,timestamp_2026-01-13 14:00:00,timestamp_2026-01-13 15:00:00,timestamp_2026-01-13 16:00:00,timestamp_2026-01-13 17:00:00,timestamp_2026-01-13 18:00:00,timestamp_2026-01-13 19:00:00,timestamp_2026-01-13 20:00:00,timestamp_2026-01-13 21:00:00,timestamp_2026-01-13 22:00:00,timestamp_2026-01-13 23:00:00,timestamp_2026-01-14 00:00:00,timestamp_2026-01-14 01:00:00,timestamp_2026-01-14 02:00:00,timestamp_2026-01-14 03:00:00,timestamp_2026-01-14 04:00:00,timestamp_2026-01-14 05:00:00,timestamp_2026-01-14 06:00:00,timestamp_2026-01-14 07:00:00,timestamp_2026-01-14 08:00:00,timestamp_2026-01-14 09:00:00,timestamp_2026-01-14 10:00:00,timestamp_2026-01-14 11:00:00,timestamp_2026-01-14 12:00:00,timestamp_2026-01-14 13:00:00,timestamp_2026-01-14 14:00:00,timestamp_2026-01-14 15:00:00,timestamp_2026-01-14 16:00:00,timestamp_2026-01-14 17:00:00,timestamp_2026-01-14 18:00:00,timestamp_2026-01-14 19:00:00,timestamp_2026-01-14 20:00:00,timestamp_2026-01-14 21:00:00,timestamp_2026-01-14 22:00:00,timestamp_2026-01-14 23:00:00,timestamp_2026-01-15 00:00:00,timestamp_2026-01-15 01:00:00,timestamp_2026-01-15 02:00:00,timestamp_2026-01-15 03:00:00,timestamp_2026-01-15 04:00:00,timestamp_2026-01-15 05:00:00,timestamp_2026-01-15 06:00:00,timestamp_2026-01-15 07:00:00,timestamp_2026-01-15 08:00:00,timestamp_2026-01-15 09:00:00,timestamp_2026-01-15 10:00:00,timestamp_2026-01-15 11:00:00,timestamp_2026-01-15 12:00:00,timestamp_2026-01-15 13:00:00,timestamp_2026-01-15 14:00:00,timestamp_2026-01-15 15:00:00,timestamp_2026-01-15 16:00:00,timestamp_2026-01-15 17:00:00,timestamp_2026-01-15 18:00:00,timestamp_2026-01-15 19:00:00,timestamp_2026-01-15 20:00:00,timestamp_2026-01-15 21:00:00,timestamp_2026-01-15 22:00:00,timestamp_2026-01-15 23:00:00,timestamp_2026-01-16 00:00:00,timestamp_2026-01-16 01:00:00,timestamp_2026-01-16 02:00:00,timestamp_2026-01-16 03:00:00,timestamp_2026-01-16 04:00:00,timestamp_2026-01-16 05:00:00,timestamp_2026-01-16 06:00:00,timestamp_2026-01-16 07:00:00,timestamp_2026-01-16 08:00:00,timestamp_2026-01-16 09:00:00,timestamp_2026-01-16 10:00:00,timestamp_2026-01-16 11:00:00,timestamp_2026-01-16 12:00:00,timestamp_2026-01-16 13:00:00,timestamp_2026-01-16 14:00:00,timestamp_2026-01-16 15:00:00,timestamp_2026-01-16 16:00:00,timestamp_2026-01-16 17:00:00,timestamp_2026-01-16 18:00:00,timestamp_2026-01-16 19:00:00,timestamp_2026-01-16 20:00:00,timestamp_2026-01-16 21:00:00,timestamp_2026-01-16 22:00:00,timestamp_2026-01-16 23:00:00,timestamp_2026-01-17 00:00:00,timestamp_2026-01-17 01:00:00,timestamp_2026-01-17 02:00:00,timestamp_2026-01-17 03:00:00,timestamp_2026-01-17 04:00:00,timestamp_2026-01-17 05:00:00,timestamp_2026-01-17 06:00:00,timestamp_2026-01-17 07:00:00,timestamp_2026-01-17 08:00:00,timestamp_2026-01-17 09:00:00,timestamp_2026-01-17 10:00:00,timestamp_2026-01-17 11:00:00,timestamp_2026-01-17 12:00:00,timestamp_2026-01-17 13:00:00,timestamp_2026-01-17 14:00:00,timestamp_2026-01-17 15:00:00,timestamp_2026-01-17 16:00:00,timestamp_2026-01-17 17:00:00,timestamp_2026-01-17 18:00:00,timestamp_2026-01-17 19:00:00,lote_producao_Lote_A,lote_producao_Lote_B,lote_producao_Lote_C,lote_producao_Lote_D,operador_op_a,operador_op_b,operador_op_c,operador_op_d,modo_controle_automatico,modo_controle_cascata,modo_controle_manual,status_valvula_intermitente,status_valvula_normal,status_valvula_travada
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,True,False
1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,True,False,False
3,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,True,False,False
4,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False

## 11. Preparação da base final para modelagem

Monte a base final usando:
- variáveis numéricas padronizadas;
- variáveis categóricas codificadas.

In [59]:
X_final = pd.concat([X_padronizado, X_categorico_codificado], axis=1)

print('Dimensão da base final de atributos:', X_final.shape)
display(X_final.head())

Dimensão da base final de atributos: (188, 203)

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3,timestamp_2026-01-10 08:00:00,timestamp_2026-01-10 09:00:00,timestamp_2026-01-10 10:00:00,timestamp_2026-01-10 11:00:00,timestamp_2026-01-10 12:00:00,timestamp_2026-01-10 13:00:00,timestamp_2026-01-10 14:00:00,timestamp_2026-01-10 15:00:00,timestamp_2026-01-10 16:00:00,timestamp_2026-01-10 17:00:00,timestamp_2026-01-10 18:00:00,timestamp_2026-01-10 19:00:00,timestamp_2026-01-10 20:00:00,timestamp_2026-01-10 21:00:00,timestamp_2026-01-10 22:00:00,timestamp_2026-01-10 23:00:00,timestamp_2026-01-11 00:00:00,timestamp_2026-01-11 01:00:00,timestamp_2026-01-11 02:00:00,timestamp_2026-01-11 03:00:00,timestamp_2026-01-11 04:00:00,timestamp_2026-01-11 05:00:00,timestamp_2026-01-11 06:00:00,timestamp_2026-01-11 07:00:00,timestamp_2026-01-11 08:00:00,timestamp_2026-01-11 09:00:00,timestamp_2026-01-11 10:00:00,timestamp_2026-01-11 11:00:00,timestamp_2026-01-11 12:00:00,timestamp_2026-01-11 13:00:00,timestamp_2026-01-11 14:00:00,timestamp_2026-01-11 15:00:00,timestamp_2026-01-11 16:00:00,timestamp_2026-01-11 17:00:00,timestamp_2026-01-11 18:00:00,timestamp_2026-01-11 19:00:00,timestamp_2026-01-11 20:00:00,timestamp_2026-01-11 21:00:00,timestamp_2026-01-11 22:00:00,timestamp_2026-01-11 23:00:00,timestamp_2026-01-12 00:00:00,timestamp_2026-01-12 01:00:00,timestamp_2026-01-12 02:00:00,timestamp_2026-01-12 03:00:00,timestamp_2026-01-12 04:00:00,timestamp_2026-01-12 05:00:00,timestamp_2026-01-12 06:00:00,timestamp_2026-01-12 07:00:00,timestamp_2026-01-12 08:00:00,timestamp_2026-01-12 09:00:00,timestamp_2026-01-12 10:00:00,timestamp_2026-01-12 11:00:00,timestamp_2026-01-12 12:00:00,timestamp_2026-01-12 13:00:00,timestamp_2026-01-12 14:00:00,timestamp_2026-01-12 15:00:00,timestamp_2026-01-12 16:00:00,timestamp_2026-01-12 17:00:00,timestamp_2026-01-12 18:00:00,timestamp_2026-01-12 19:00:00,timestamp_2026-01-12 20:00:00,timestamp_2026-01-12 21:00:00,timestamp_2026-01-12 22:00:00,timestamp_2026-01-12 23:00:00,timestamp_2026-01-13 00:00:00,timestamp_2026-01-13 01:00:00,timestamp_2026-01-13 02:00:00,timestamp_2026-01-13 03:00:00,timestamp_2026-01-13 04:00:00,timestamp_2026-01-13 05:00:00,timestamp_2026-01-13 06:00:00,timestamp_2026-01-13 07:00:00,timestamp_2026-01-13 08:00:00,timestamp_2026-01-13 09:00:00,timestamp_2026-01-13 10:00:00,timestamp_2026-01-13 11:00:00,timestamp_2026-01-13 12:00:00,timestamp_2026-01-13 13:00:00,timestamp_2026-01-13 14:00:00,timestamp_2026-01-13 15:00:00,timestamp_2026-01-13 16:00:00,timestamp_2026-01-13 17:00:00,timestamp_2026-01-13 18:00:00,timestamp_2026-01-13 19:00:00,timestamp_2026-01-13 20:00:00,timestamp_2026-01-13 21:00:00,timestamp_2026-01-13 22:00:00,timestamp_2026-01-13 23:00:00,timestamp_2026-01-14 00:00:00,timestamp_2026-01-14 01:00:00,timestamp_2026-01-14 02:00:00,timestamp_2026-01-14 03:00:00,timestamp_2026-01-14 04:00:00,timestamp_2026-01-14 05:00:00,timestamp_2026-01-14 06:00:00,timestamp_2026-01-14 07:00:00,timestamp_2026-01-14 08:00:00,timestamp_2026-01-14 09:00:00,timestamp_2026-01-14 10:00:00,timestamp_2026-01-14 11:00:00,timestamp_2026-01-14 12:00:00,timestamp_2026-01-14 13:00:00,timestamp_2026-01-14 14:00:00,timestamp_2026-01-14 15:00:00,timestamp_2026-01-14 16:00:00,timestamp_2026-01-14 17:00:00,timestamp_2026-01-14 18:00:00,timestamp_2026-01-14 19:00:00,timestamp_2026-01-14 20:00:00,timestamp_2026-01-14 21:00:00,timestamp_2026-01-14 22:00:00,timestamp_2026-01-14 23:00:00,timestamp_2026-01-15 00:00:00,timestamp_2026-01-15 01:00:00,timestamp_2026-01-15 02:00:00,timestamp_2026-01-15 03:00:00,timestamp_2026-01-15 04:00:00,timestamp_2026-01-15 05:00:00,timestamp_2026-01-15 06:00:00,timestamp_2026-01-15 07:00:00,timestamp_2026-01-15 08:00:00,timestamp_2026-01-15 09:00:00,timestamp_2026-01-15 10:00:00,timestamp_2026-01-15 11:00:00,timestamp_2026-01-15 12:00:00,timestamp_2026-01-15 13:00:00,timestamp_2026-01-15 14:00:00,timestamp_2026-01-15 15:00:00,timestamp_2026-01-15 16:00:00,timestamp_2026-01-15 17:00:00,timestamp_2026-01-15 18:00:00,timestamp_2026-01-15 19:00:00,timestamp_2026-01-15 20:00:00,timestamp_2026-01-15 21:00:00,timestamp_2026-01-15 22:00:00,timestamp_2026-01-15 23:00:00,timestamp_2026-01-16 00:00:00,timestamp_2026-01-16 01:00:00,timestamp_2026-01-16 02:00:00,timestamp_2026-01-16 03:00:00,timestamp_2026-01-16 04:00:00,timestamp_2026-01-16 05:00:00,timestamp_2026-01-16 06:00:00,timestamp_2026-01-16 07:00:00,timestamp_2026-01-16 08:00:00,timestamp_2026-01-16 09:00:00,timestamp_2026-01-16 10:00:00,timestamp_2026-01-16 11:00:00,timestamp_2026-01-16 12:00:00,timestamp_2026-01-16 13:00:00,timestamp_2026-01-16 14:00:00,timestamp_2026-01-16 15:00:00,timestamp_2026-01-16 16:00:00,timestamp_2026-01-16 17:00:00,timestamp_2026-01-16 18:00:00,timestamp_2026-01-16 19:00:00,timestamp_2026-01-16 20:00:00,timestamp_2026-01-16 21:00:00,timestamp_2026-01-16 22:00:00,timestamp_2026-01-16 23:00:00,timestamp_2026-01-17 00:00:00,timestamp_2026-01-17 01:00:00,timestamp_2026-01-17 02:00:00,timestamp_2026-01-17 03:00:00,timestamp_2026-01-17 04:00:00,timestamp_2026-01-17 05:00:00,timestamp_2026-01-17 06:00:00,timestamp_2026-01-17 07:00:00,timestamp_2026-01-17 08:00:00,timestamp_2026-01-17 09:00:00,timestamp_2026-01-17 10:00:00,timestamp_2026-01-17 11:00:00,timestamp_2026-01-17 12:00:00,timestamp_2026-01-17 13:00:00,timestamp_2026-01-17 14:00:00,timestamp_2026-01-17 15:00:00,timestamp_2026-01-17 16:00:00,timestamp_2026-01-17 17:00:00,timestamp_2026-01-17 18:00:00,timestamp_2026-01-17 19:00:00,lote_producao_Lote_A,lote_producao_Lote_B,lote_producao_Lote_C,lote_producao_Lote_D,operador_op_a,operador_op_b,operador_op_c,operador_op_d,modo_controle_automatico,modo_controle_cascata,modo_controle_manual,status_valvula_intermitente,status_valvula_normal,status_valvula_travada
0,0.196487,0.617912,-0.520001,5.454692,-0.091729,0.652787,-0.904175,0.909975,0.931345,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,True,False
1,0.586374,-0.018284,0.787201,-0.056996,0.293278,0.205000,0.503087,0.588996,0.412936,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False
2,0.781729,0.692716,0.194317,-0.341863,0.285932,-0.161181,-0.412837,-0.277647,-0.623884,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,True,False,False
3,-1.034995,-1.226766,-0.485475,0.007019,0.384480,0.456095,1.156653,-0.438136,1.708960,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,True,False,False
4,-1.439720,NaN,0.155030,6.201533,1.551742,0.875634,-0.419046,-0.470234,-1.174695,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False

## 12. Consolidação com a variável-alvo

In [62]:
base_final_modelagem = X_final.copy()
base_final_modelagem[alvo] = y

print('Dimensão da base final completa:', base_final_modelagem.shape)
display(base_final_modelagem.head())

Dimensão da base final completa: (188, 204)

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3,timestamp_2026-01-10 08:00:00,timestamp_2026-01-10 09:00:00,timestamp_2026-01-10 10:00:00,timestamp_2026-01-10 11:00:00,timestamp_2026-01-10 12:00:00,timestamp_2026-01-10 13:00:00,timestamp_2026-01-10 14:00:00,timestamp_2026-01-10 15:00:00,timestamp_2026-01-10 16:00:00,timestamp_2026-01-10 17:00:00,timestamp_2026-01-10 18:00:00,timestamp_2026-01-10 19:00:00,timestamp_2026-01-10 20:00:00,timestamp_2026-01-10 21:00:00,timestamp_2026-01-10 22:00:00,timestamp_2026-01-10 23:00:00,timestamp_2026-01-11 00:00:00,timestamp_2026-01-11 01:00:00,timestamp_2026-01-11 02:00:00,timestamp_2026-01-11 03:00:00,timestamp_2026-01-11 04:00:00,timestamp_2026-01-11 05:00:00,timestamp_2026-01-11 06:00:00,timestamp_2026-01-11 07:00:00,timestamp_2026-01-11 08:00:00,timestamp_2026-01-11 09:00:00,timestamp_2026-01-11 10:00:00,timestamp_2026-01-11 11:00:00,timestamp_2026-01-11 12:00:00,timestamp_2026-01-11 13:00:00,timestamp_2026-01-11 14:00:00,timestamp_2026-01-11 15:00:00,timestamp_2026-01-11 16:00:00,timestamp_2026-01-11 17:00:00,timestamp_2026-01-11 18:00:00,timestamp_2026-01-11 19:00:00,timestamp_2026-01-11 20:00:00,timestamp_2026-01-11 21:00:00,timestamp_2026-01-11 22:00:00,timestamp_2026-01-11 23:00:00,timestamp_2026-01-12 00:00:00,timestamp_2026-01-12 01:00:00,timestamp_2026-01-12 02:00:00,timestamp_2026-01-12 03:00:00,timestamp_2026-01-12 04:00:00,timestamp_2026-01-12 05:00:00,timestamp_2026-01-12 06:00:00,timestamp_2026-01-12 07:00:00,timestamp_2026-01-12 08:00:00,timestamp_2026-01-12 09:00:00,timestamp_2026-01-12 10:00:00,timestamp_2026-01-12 11:00:00,timestamp_2026-01-12 12:00:00,timestamp_2026-01-12 13:00:00,timestamp_2026-01-12 14:00:00,timestamp_2026-01-12 15:00:00,timestamp_2026-01-12 16:00:00,timestamp_2026-01-12 17:00:00,timestamp_2026-01-12 18:00:00,timestamp_2026-01-12 19:00:00,timestamp_2026-01-12 20:00:00,timestamp_2026-01-12 21:00:00,timestamp_2026-01-12 22:00:00,timestamp_2026-01-12 23:00:00,timestamp_2026-01-13 00:00:00,timestamp_2026-01-13 01:00:00,timestamp_2026-01-13 02:00:00,timestamp_2026-01-13 03:00:00,timestamp_2026-01-13 04:00:00,timestamp_2026-01-13 05:00:00,timestamp_2026-01-13 06:00:00,timestamp_2026-01-13 07:00:00,timestamp_2026-01-13 08:00:00,timestamp_2026-01-13 09:00:00,timestamp_2026-01-13 10:00:00,timestamp_2026-01-13 11:00:00,timestamp_2026-01-13 12:00:00,timestamp_2026-01-13 13:00:00,timestamp_2026-01-13 14:00:00,timestamp_2026-01-13 15:00:00,timestamp_2026-01-13 16:00:00,timestamp_2026-01-13 17:00:00,timestamp_2026-01-13 18:00:00,timestamp_2026-01-13 19:00:00,timestamp_2026-01-13 20:00:00,timestamp_2026-01-13 21:00:00,timestamp_2026-01-13 22:00:00,timestamp_2026-01-13 23:00:00,timestamp_2026-01-14 00:00:00,timestamp_2026-01-14 01:00:00,timestamp_2026-01-14 02:00:00,timestamp_2026-01-14 03:00:00,timestamp_2026-01-14 04:00:00,timestamp_2026-01-14 05:00:00,timestamp_2026-01-14 06:00:00,timestamp_2026-01-14 07:00:00,timestamp_2026-01-14 08:00:00,timestamp_2026-01-14 09:00:00,timestamp_2026-01-14 10:00:00,timestamp_2026-01-14 11:00:00,timestamp_2026-01-14 12:00:00,timestamp_2026-01-14 13:00:00,timestamp_2026-01-14 14:00:00,timestamp_2026-01-14 15:00:00,timestamp_2026-01-14 16:00:00,timestamp_2026-01-14 17:00:00,timestamp_2026-01-14 18:00:00,timestamp_2026-01-14 19:00:00,timestamp_2026-01-14 20:00:00,timestamp_2026-01-14 21:00:00,timestamp_2026-01-14 22:00:00,timestamp_2026-01-14 23:00:00,timestamp_2026-01-15 00:00:00,timestamp_2026-01-15 01:00:00,timestamp_2026-01-15 02:00:00,timestamp_2026-01-15 03:00:00,timestamp_2026-01-15 04:00:00,timestamp_2026-01-15 05:00:00,timestamp_2026-01-15 06:00:00,timestamp_2026-01-15 07:00:00,timestamp_2026-01-15 08:00:00,timestamp_2026-01-15 09:00:00,timestamp_2026-01-15 10:00:00,timestamp_2026-01-15 11:00:00,timestamp_2026-01-15 12:00:00,timestamp_2026-01-15 13:00:00,timestamp_2026-01-15 14:00:00,timestamp_2026-01-15 15:00:00,timestamp_2026-01-15 16:00:00,timestamp_2026-01-15 17:00:00,timestamp_2026-01-15 18:00:00,timestamp_2026-01-15 19:00:00,timestamp_2026-01-15 20:00:00,timestamp_2026-01-15 21:00:00,timestamp_2026-01-15 22:00:00,timestamp_2026-01-15 23:00:00,timestamp_2026-01-16 00:00:00,timestamp_2026-01-16 01:00:00,timestamp_2026-01-16 02:00:00,timestamp_2026-01-16 03:00:00,timestamp_2026-01-16 04:00:00,timestamp_2026-01-16 05:00:00,timestamp_2026-01-16 06:00:00,timestamp_2026-01-16 07:00:00,timestamp_2026-01-16 08:00:00,timestamp_2026-01-16 09:00:00,timestamp_2026-01-16 10:00:00,timestamp_2026-01-16 11:00:00,timestamp_2026-01-16 12:00:00,timestamp_2026-01-16 13:00:00,timestamp_2026-01-16 14:00:00,timestamp_2026-01-16 15:00:00,timestamp_2026-01-16 16:00:00,timestamp_2026-01-16 17:00:00,timestamp_2026-01-16 18:00:00,timestamp_2026-01-16 19:00:00,timestamp_2026-01-16 20:00:00,timestamp_2026-01-16 21:00:00,timestamp_2026-01-16 22:00:00,timestamp_2026-01-16 23:00:00,timestamp_2026-01-17 00:00:00,timestamp_2026-01-17 01:00:00,timestamp_2026-01-17 02:00:00,timestamp_2026-01-17 03:00:00,timestamp_2026-01-17 04:00:00,timestamp_2026-01-17 05:00:00,timestamp_2026-01-17 06:00:00,timestamp_2026-01-17 07:00:00,timestamp_2026-01-17 08:00:00,timestamp_2026-01-17 09:00:00,timestamp_2026-01-17 10:00:00,timestamp_2026-01-17 11:00:00,timestamp_2026-01-17 12:00:00,timestamp_2026-01-17 13:00:00,timestamp_2026-01-17 14:00:00,timestamp_2026-01-17 15:00:00,timestamp_2026-01-17 16:00:00,timestamp_2026-01-17 17:00:00,timestamp_2026-01-17 18:00:00,timestamp_2026-01-17 19:00:00,lote_producao_Lote_A,lote_producao_Lote_B,lote_producao_Lote_C,lote_producao_Lote_D,operador_op_a,operador_op_b,operador_op_c,operador_op_d,modo_controle_automatico,modo_controle_cascata,modo_controle_manual,status_valvula_intermitente,status_valvula_normal,status_valvula_travada,status_instrumentacao
0,0.196487,0.617912,-0.520001,5.454692,-0.091729,0.652787,-0.904175,0.909975,0.931345,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,True,False,estavel
1,0.586374,-0.018284,0.787201,-0.056996,0.293278,0.205000,0.503087,0.588996,0.412936,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,inspecao
2,0.781729,0.692716,0.194317,-0.341863,0.285932,-0.161181,-0.412837,-0.277647,-0.623884,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,True,False,False,inspecao
3,-1.034995,-1.226766,-0.485475,0.007019,0.384480,0.456095,1.156653,-0.438136,1.708960,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,True,False,False,inspecao
4,-1.439720,NaN,0.155030,6.201533,1.551742,0.875634,-0.419046,-0.470234,-1.174695,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False,estavel

## 13. Verificações finais

In [61]:
display(
    base_final_modelagem.isnull()
    .sum()
    .rename_axis('coluna')
    .reset_index(name='faltantes')
)

display(
    base_final_modelagem.dtypes
    .rename_axis('coluna')
    .reset_index(name='tipo')
)

                          coluna  faltantes
0           setpoint_vazao_l_min          0
1             vazao_medida_l_min         12
2              pressao_linha_bar         10
3         temperatura_processo_c         10
4           abertura_valvula_pct          0
..                           ...        ...
199         modo_controle_manual          0
200  status_valvula_intermitente          0
201        status_valvula_normal          0
202       status_valvula_travada          0
203        status_instrumentacao          0

[204 rows x 2 columns]

                          coluna     tipo
0           setpoint_vazao_l_min  float64
1             vazao_medida_l_min  float64
2              pressao_linha_bar  float64
3         temperatura_processo_c  float64
4           abertura_valvula_pct  float64
..                           ...      ...
199         modo_controle_manual     bool
200  status_valvula_intermitente     bool
201        status_valvula_normal     bool
202       status_valvula_travada     bool
203        status_instrumentacao   object

[204 rows x 2 columns]

## 14. Exportação dos arquivos

Salve os arquivos finais para uso nas próximas aulas.

In [45]:
# Complete os comandos abaixo
X_final.to_csv('____________________________', index=False)
base_final_modelagem.to_csv('____________________________', index=False)

print('Arquivos exportados com sucesso.')

Arquivos exportados com sucesso.

## 15. Fechamento da aula

**Escreva, com suas palavras, o que foi feito nesta aula:**  
- separação entre atributos e alvo;  
- normalização e padronização;  
- codificação de variáveis categóricas;  
- preparação final da base para modelagem.

Nesta aula, aprendemos a separar os atributos do alvo, normalizar e padronizar os dados, transformar variáveis categóricas em números e preparar a base para a modelagem. Essas etapas garantem que os dados estejam organizados e adequados para o uso em modelos de Machine Learning.