<a href="https://colab.research.google.com/github/guslimaa777/45419370/blob/main/aula3_machine_learning_industria_aluno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 3 — Preparação final da base para modelagem

## Contexto
Nesta aula, continuaremos o projeto de **Machine Learning Aplicada à Indústria**, utilizando a base de dados de uma planta química com foco no monitoramento do **status da instrumentação** de um sistema de controle de vazão de produtos químicos.

## Foco da aula
- normalização e padronização
- codificação de variáveis categóricas
- preparação final da base para modelagem

## Resultado esperado
Ao final da aula, a turma deverá gerar uma base pronta para modelagem, com variáveis numéricas escaladas, variáveis categóricas codificadas e separação entre atributos preditores e variável-alvo.

## Orientações ao aluno
Complete as células indicadas com base na demonstração guiada do professor.  
Registre observações técnicas sempre que solicitado.

In [143]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

pd.set_option('display.max_columns', None)

## 1. Carregamento da base

Tente carregar primeiro a base tratada da aula anterior.  
Se necessário, utilize a base bruta para fins de prática.

In [144]:
import pandas as pd

# Utilize o caminho do arquivo fornecido pelo usuário
file_path = '/content/dados_aula2_tratados (1).csv'

try:
    df = pd.read_csv(file_path)
    print(f'Base carregada: {file_path}')
except FileNotFoundError:
    print(f'Erro: O arquivo {file_path} não foi encontrado. Por favor, verifique o caminho.')
    df = None # Define df como None em caso de erro para evitar NameError

if df is not None:
    display(df.head())

Base carregada: /content/dados_aula2_tratados (1).csv

,timestamp,lote_producao,operador,modo_controle,status_valvula,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3,status_instrumentacao
0,2026-01-10 08:00:00,Lote_A,op_b,automatico,normal,121.44,128.080,3.518,55.55625,56.97,2.960,220.8,7.09,1.069,estavel
1,2026-01-10 09:00:00,Lote_D,op_c,cascata,normal,126.17,119.320,4.616,43.34000,63.26,2.532,402.1,6.99,1.053,inspecao
2,2026-01-10 10:00:00,Lote_B,op_d,manual,intermitente,128.54,129.110,4.118,40.67000,63.14,2.182,284.1,6.72,1.021,inspecao
3,2026-01-10 11:00:00,Lote_C,op_a,automatico,intermitente,106.50,102.680,3.547,43.94000,64.75,2.772,486.3,6.67,1.093,inspecao
4,2026-01-10 12:00:00,Lote_C,op_a,automatico,normal,101.59,118.565,4.085,55.55625,83.82,3.173,283.3,6.66,1.004,estavel

## 2. Inspeção inicial da base

Preencha os comandos para visualizar:
- dimensão da base;
- tipos de dados;
- nomes das colunas.

In [145]:


# Exiba a dimensão da base
print('Dimensão da base:', df.shape)

# Exiba os tipos de dados
display(df.dtypes)

# Exiba os nomes das colunas
display(pd.DataFrame({'coluna': df.columns}))

Dimensão da base: (180, 15)

timestamp                   object
lote_producao               object
operador                    object
modo_controle               object
status_valvula              object
setpoint_vazao_l_min       float64
vazao_medida_l_min         float64
pressao_linha_bar          float64
temperatura_processo_c     float64
abertura_valvula_pct       float64
vibracao_bomba_mm_s        float64
tempo_resposta_ms          float64
ph_produto                 float64
densidade_produto_g_cm3    float64
status_instrumentacao       object
dtype: object

                     coluna
0                 timestamp
1             lote_producao
2                  operador
3             modo_controle
4            status_valvula
5      setpoint_vazao_l_min
6        vazao_medida_l_min
7         pressao_linha_bar
8    temperatura_processo_c
9      abertura_valvula_pct
10      vibracao_bomba_mm_s
11        tempo_resposta_ms
12               ph_produto
13  densidade_produto_g_cm3
14    status_instrumentacao

## 3. Identificação de colunas numéricas e categóricas

In [146]:

colunas_numericas = df.select_dtypes(include=['number']).columns.tolist()
colunas_categoricas = df.select_dtypes(include=['object', 'category']).columns.tolist()

print('Colunas numéricas:', colunas_numericas)
print('\nColunas categóricas:', colunas_categoricas)

Colunas numéricas: ['setpoint_vazao_l_min', 'vazao_medida_l_min', 'pressao_linha_bar', 'temperatura_processo_c', 'abertura_valvula_pct', 'vibracao_bomba_mm_s', 'tempo_resposta_ms', 'ph_produto', 'densidade_produto_g_cm3']

Colunas categóricas: ['timestamp', 'lote_producao', 'operador', 'modo_controle', 'status_valvula', 'status_instrumentacao']

**Registro do aluno:**  
Quais colunas parecem mais importantes para o problema industrial?  
- Resposta:

## 4. Separação da variável-alvo

Utilize como variável-alvo a coluna `status_instrumentacao`.

In [147]:

alvo = 'status_instrumentacao'

X = df.drop(columns=[alvo]).copy()
y = df[alvo].copy()

print('Dimensão de X:', X.shape)
print('Dimensão de y:', y.shape)

display(
    y.value_counts(dropna=False)
     .rename_axis('classe')
     .reset_index(name='quantidade')
)

Dimensão de X: (180, 14)
Dimensão de y: (180,)

     classe  quantidade
0  inspecao         116
1   estavel          64

## 5. Separação entre dados numéricos e categóricos

In [148]:
X_numerico = X.select_dtypes(include=['int64', 'float64']).copy()
X_categorico = X.select_dtypes(include=["object", "category"]).copy()

print('dimensao de x_numerico:', X_numerico.shape)
print('dimensao de x_categorico:', X_categorico.shape)

display(X_categorico.head())
display(X_numerico.head())

dimensao de x_numerico: (180, 9)
dimensao de x_categorico: (180, 5)

             timestamp lote_producao operador modo_controle status_valvula
0  2026-01-10 08:00:00        Lote_A     op_b    automatico         normal
1  2026-01-10 09:00:00        Lote_D     op_c       cascata         normal
2  2026-01-10 10:00:00        Lote_B     op_d        manual   intermitente
3  2026-01-10 11:00:00        Lote_C     op_a    automatico   intermitente
4  2026-01-10 12:00:00        Lote_C     op_a    automatico         normal

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3
0,121.44,128.080,3.518,55.55625,56.97,2.960,220.8,7.09,1.069
1,126.17,119.320,4.616,43.34000,63.26,2.532,402.1,6.99,1.053
2,128.54,129.110,4.118,40.67000,63.14,2.182,284.1,6.72,1.021
3,106.50,102.680,3.547,43.94000,64.75,2.772,486.3,6.67,1.093
4,101.59,118.565,4.085,55.55625,83.82,3.173,283.3,6.66,1.004

## 6. Normalização

Complete o código para aplicar `MinMaxScaler` nas variáveis numéricas.

In [149]:
scaler_minmax = MinMaxScaler()

X_normalizado_array = scaler_minmax.fit_transform(X_numerico)

X_normalizado = pd.DataFrame(
    X_normalizado_array,
    columns=X_numerico.columns,
    index=X_numerico.index
)

X_normalizado.head()

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3
0,0.466897,0.578050,0.335708,1.000000,0.479390,0.691935,0.197053,0.690789,0.648649
1,0.537907,0.444266,0.857075,0.507211,0.556786,0.576882,0.708333,0.625000,0.562162
2,0.573487,0.593780,0.620608,0.399506,0.555309,0.482796,0.375564,0.447368,0.389189
3,0.242606,0.190138,0.349478,0.531414,0.575120,0.641398,0.945784,0.414474,0.778378
4,0.168894,0.432736,0.604938,1.000000,0.809770,0.749194,0.373308,0.407895,0.297297

## 7. Comparação antes e depois da normalização

In [150]:
comparacao_normalizacao = pd.DataFrame({
    'valor_original_min': [X_numerico['setpoint_vazao_l_min'].min()],
    'valor_original_max': [X_numerico['setpoint_vazao_l_min'].max()],
    'valor_normalizado_min': [X_normalizado['setpoint_vazao_l_min'].min()],
    'valor_normalizado_max': [X_normalizado['setpoint_vazao_l_min'].max()]
})

display(comparacao_normalizacao)

,valor_original_min,valor_original_max,valor_normalizado_min,valor_normalizado_max
0,90.34,156.95,0.0,1.0

**Registro do aluno:**  
O que mudou nos dados após a normalização?  
- Resposta:

## 8. Padronização

Agora aplique `StandardScaler` às variáveis numéricas.

In [151]:

scaler_standard = StandardScaler()

X_padronizado_array = scaler_standard.fit_transform(X_numerico)

X_padronizado = pd.DataFrame(
    X_padronizado_array,
    columns=X_numerico.columns,
    index=X_numerico.index
)

X_padronizado.head()

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3
0,0.191198,0.639145,-0.856294,2.317030,-0.096176,0.971771,-1.574939,0.916810,0.922717
1,0.577176,-0.021791,1.750977,0.040508,0.290154,0.368680,1.087681,0.595436,0.400630
2,0.770573,0.716858,0.568444,-0.457051,0.282783,-0.124501,-0.645298,-0.272276,-0.643545
3,-1.027936,-1.277268,-0.787432,0.152319,0.381669,0.706862,2.324265,-0.432963,1.705849
4,-1.428602,-0.078755,0.490084,2.317030,1.552943,1.271907,-0.657047,-0.465100,-1.198264

## 9. Comparação antes e depois da padronização

In [165]:

comparacao_padronizacao = pd.DataFrame({
    'media_original': X_numerico.mean(),
    'desvio_original': X_numerico.std(),
    'media_padronizada': X_padronizado.mean(),
    'desvio_padronizado': X_padronizado.std()
})

display(comparacao_padronizacao.round(4))

,media_original,desvio_original,media_padronizada,desvio_padronizado
setpoint_vazao_l_min,119.0969,12.2888,-0.0,1.0028
vazao_medida_l_min,119.6088,13.2909,0.0,1.0028
pressao_linha_bar,3.8786,0.4223,0.0,1.0028
temperatura_processo_c,43.1226,5.3812,0.0,1.0028
abertura_valvula_pct,58.5359,16.3268,0.0,1.0028
vibracao_bomba_mm_s,2.2704,0.7117,-0.0,1.0028
tempo_resposta_ms,328.0389,68.2808,-0.0,1.0028
ph_produto,6.8047,0.3120,-0.0,1.0028
densidade_produto_g_cm3,1.0407,0.0307,0.0,1.0028

**Registro do aluno:**  
Quando a padronização pode ser mais útil que a normalização?  
- Resposta:

## 10. Codificação de variáveis categóricas

Utilize `pd.get_dummies()` para transformar as variáveis categóricas em colunas numéricas.

In [158]:
X_categorico_codificado = pd.get_dummies(X_categorico, drop_first=False)
X_categorico['timestamp']=pd.to_datetime(X_categorico['timestamp'])
print('dimensao da base categorica', X_categorico.nunique())
print('Dimensão da base categórica codificada:', X_categorico_codificado.shape)
X_categorico_codificado.head()

dimensao da base categorica timestamp         180
lote_producao       4
operador            4
modo_controle       3
status_valvula      3
dtype: int64
Dimensão da base categórica codificada: (180, 15)

,timestamp,lote_producao_Lote_A,lote_producao_Lote_B,lote_producao_Lote_C,lote_producao_Lote_D,operador_op_a,operador_op_b,operador_op_c,operador_op_d,modo_controle_automatico,modo_controle_cascata,modo_controle_manual,status_valvula_intermitente,status_valvula_normal,status_valvula_travada
0,2026-01-10 08:00:00,True,False,False,False,False,True,False,False,True,False,False,False,True,False
1,2026-01-10 09:00:00,False,False,False,True,False,False,True,False,False,True,False,False,True,False
2,2026-01-10 10:00:00,False,True,False,False,False,False,False,True,False,False,True,True,False,False
3,2026-01-10 11:00:00,False,False,True,False,True,False,False,False,True,False,False,True,False,False
4,2026-01-10 12:00:00,False,False,True,False,True,False,False,False,True,False,False,False,True,False

## 11. Preparação da base final para modelagem

Monte a base final usando:
- variáveis numéricas padronizadas;
- variáveis categóricas codificadas.

In [168]:
X_final = pd.concat([X_padronizado, X_categorico_codificado], axis=1)

print('Dimensão da base final de atributos:', X_final.shape)
display(X_final.head())

Dimensão da base final de atributos: (180, 24)

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3,timestamp,lote_producao_Lote_A,lote_producao_Lote_B,lote_producao_Lote_C,lote_producao_Lote_D,operador_op_a,operador_op_b,operador_op_c,operador_op_d,modo_controle_automatico,modo_controle_cascata,modo_controle_manual,status_valvula_intermitente,status_valvula_normal,status_valvula_travada
0,0.191198,0.639145,-0.856294,2.317030,-0.096176,0.971771,-1.574939,0.916810,0.922717,2026-01-10 08:00:00,True,False,False,False,False,True,False,False,True,False,False,False,True,False
1,0.577176,-0.021791,1.750977,0.040508,0.290154,0.368680,1.087681,0.595436,0.400630,2026-01-10 09:00:00,False,False,False,True,False,False,True,False,False,True,False,False,True,False
2,0.770573,0.716858,0.568444,-0.457051,0.282783,-0.124501,-0.645298,-0.272276,-0.643545,2026-01-10 10:00:00,False,True,False,False,False,False,False,True,False,False,True,True,False,False
3,-1.027936,-1.277268,-0.787432,0.152319,0.381669,0.706862,2.324265,-0.432963,1.705849,2026-01-10 11:00:00,False,False,True,False,True,False,False,False,True,False,False,True,False,False
4,-1.428602,-0.078755,0.490084,2.317030,1.552943,1.271907,-0.657047,-0.465100,-1.198264,2026-01-10 12:00:00,False,False,True,False,True,False,False,False,True,False,False,False,True,False

## 12. Consolidação com a variável-alvo

In [170]:
base_final_modelagem = X_final.copy()
base_final_modelagem[alvo] = y

print('Dimensão da base final completa:', base_final_modelagem.shape)
display(base_final_modelagem.head())

Dimensão da base final completa: (180, 25)

,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3,timestamp,lote_producao_Lote_A,lote_producao_Lote_B,lote_producao_Lote_C,lote_producao_Lote_D,operador_op_a,operador_op_b,operador_op_c,operador_op_d,modo_controle_automatico,modo_controle_cascata,modo_controle_manual,status_valvula_intermitente,status_valvula_normal,status_valvula_travada,status_instrumentacao
0,0.191198,0.639145,-0.856294,2.317030,-0.096176,0.971771,-1.574939,0.916810,0.922717,2026-01-10 08:00:00,True,False,False,False,False,True,False,False,True,False,False,False,True,False,estavel
1,0.577176,-0.021791,1.750977,0.040508,0.290154,0.368680,1.087681,0.595436,0.400630,2026-01-10 09:00:00,False,False,False,True,False,False,True,False,False,True,False,False,True,False,inspecao
2,0.770573,0.716858,0.568444,-0.457051,0.282783,-0.124501,-0.645298,-0.272276,-0.643545,2026-01-10 10:00:00,False,True,False,False,False,False,False,True,False,False,True,True,False,False,inspecao
3,-1.027936,-1.277268,-0.787432,0.152319,0.381669,0.706862,2.324265,-0.432963,1.705849,2026-01-10 11:00:00,False,False,True,False,True,False,False,False,True,False,False,True,False,False,inspecao
4,-1.428602,-0.078755,0.490084,2.317030,1.552943,1.271907,-0.657047,-0.465100,-1.198264,2026-01-10 12:00:00,False,False,True,False,True,False,False,False,True,False,False,False,True,False,estavel

## 13. Verificações finais

In [164]:
display(
    base_final_modelagem.isnull()
    .sum()
    .rename_axis('coluna')
    .reset_index(name='faltantes')
)

display(
    base_final_modelagem.dtypes
    .rename_axis('coluna')
    .reset_index(name='tipo')
)

                         coluna  faltantes
0          setpoint_vazao_l_min          0
1            vazao_medida_l_min          0
2             pressao_linha_bar          0
3        temperatura_processo_c          0
4          abertura_valvula_pct          0
5           vibracao_bomba_mm_s          0
6             tempo_resposta_ms          0
7                    ph_produto          0
8       densidade_produto_g_cm3          0
9                     timestamp          0
10         lote_producao_Lote_A          0
11         lote_producao_Lote_B          0
12         lote_producao_Lote_C          0
13         lote_producao_Lote_D          0
14                operador_op_a          0
15                operador_op_b          0
16                operador_op_c          0
17                operador_op_d          0
18     modo_controle_automatico          0
19        modo_controle_cascata          0
20         modo_controle_manual          0
21  status_valvula_intermitente          0
22        status_valvula_normal          0
23       status_valvula_travada          0
24        status_instrumentacao          0

                         coluna            tipo
0          setpoint_vazao_l_min         float64
1            vazao_medida_l_min         float64
2             pressao_linha_bar         float64
3        temperatura_processo_c         float64
4          abertura_valvula_pct         float64
5           vibracao_bomba_mm_s         float64
6             tempo_resposta_ms         float64
7                    ph_produto         float64
8       densidade_produto_g_cm3         float64
9                     timestamp  datetime64[ns]
10         lote_producao_Lote_A            bool
11         lote_producao_Lote_B            bool
12         lote_producao_Lote_C            bool
13         lote_producao_Lote_D            bool
14                operador_op_a            bool
15                operador_op_b            bool
16                operador_op_c            bool
17                operador_op_d            bool
18     modo_controle_automatico            bool
19        modo_controle_cascata            bool
20         modo_controle_manual            bool
21  status_valvula_intermitente            bool
22        status_valvula_normal            bool
23       status_valvula_travada            bool
24        status_instrumentacao          object

## 14. Exportação dos arquivos

Salve os arquivos finais para uso nas próximas aulas.

In [171]:
# Complete os comandos abaixo
X_final.to_csv('____________________________', index=False)
base_final_modelagem.to_csv('____________________________', index=False)

print('Arquivos exportados com sucesso.')

Arquivos exportados com sucesso.

## 15. Fechamento da aula

**Escreva, com suas palavras, o que foi feito nesta aula:**  
- separação entre atributos e alvo;  
- normalização e padronização;  
- codificação de variáveis categóricas;  
- preparação final da base para modelagem.

Nesta aula, aprendemos a separar os atributos do alvo, normalizar e padronizar os dados, transformar variáveis categóricas em números e preparar a base para a modelagem. Essas etapas garantem que os dados estejam organizados e adequados para o uso em modelos de Machine Learning.